export const Font = {
  NunitoSansRegular: 'NunitoSans-Regular',
  NunitoSansExtraLight: 'RedHatDisplay-SemiBold',
  NunitoSansLight: 'RedHatDisplay-Bold',
  NunitoSansSemiBold: 'Suranna',
  NunitoSansBold: 'nunitosans-bold',
  NunitoSansExtraBold: 'Roboto-Medium',
  NunitoSansBlack: 'Roboto-Medium',
  NunitoSansItalic: 'Roboto-Medium',
  NunitoSansExtraLightItalic: 'Roboto-Medium',
  NunitoSansLightItalic: 'Roboto-Medium',
  NunitoSansSemiBoldItalic: 'Roboto-Medium',
  NunitoSansBoldItalic: 'Roboto-Medium',
  NunitoSansExtraBoldItalic: 'Roboto-Medium',
  NunitoSansBlackItalic: 'Roboto-Medium',
};
